### ISSUE TITLE
Exceptions are not showing in the console

### ISSUE THREAD

**Issue by mmustala** [gemgento/rails_script#11]
Hi,
I love the way this gem helps me to manage my coffee scripts. There is just one thing I'm missing, the error messages. Whenever there is a bug in my scripts the browsers javascript console shows nothing and I need to put console.log commands and refresh many times to find out the line where the bug is.

Is this behaviour expected? Or is it just my environments that does it?

**Comment by kpheasey** [comment]
I have never experienced that behavior related to exceptions not being printed.

The need to refresh multiple times before seeing changes sounds like a cache issue.  I have noticed that assets sometimes get cached, restarting the rails server always fixed that.

What exceptions are not being printed?  If you enter an undefined method, do you see an exception in the console?

**Comment by mmustala** [comment]
Hahaa, I had unselected the show javascript errors in my browser console. Thank you and sorry :)
