### ISSUE TITLE
Installation issue: Per controller/view code not firing :-/

### ISSUE THREAD

**Issue by edelgado** [gemgento/rails_script#14]
Hi @kpheasey, this gem looks great to organize JS code in Rails and I'd love to use it, but I'm running into an issue; even though every seems that it installed properly, my JS code just won't fire.

`include_rails_script` seems to be working as I see that my pages generate the proper DIV with the controller name in it:

```html
<!-- /shipments/1/edit? -->
<div id="rails-script" data-controller="Shipments" data-vars="{}"></div>
```

My `app/assets/javascripts/shipments.js.coffee` file has:

```javascript
window.App ||= {}

class App.Shipments extends App.Base

  edit: =>
    console.log "In Shipments Edit page!"
```

If I inspect the loaded scripts via Chrome's dev console, I see that the generated file (`/assets/shipments.self-d87964dbebfb5ea692519563a08b76f8cbabc30132b4a311cdb4bd1937cbc66c.js?body=1`) is:

```javascript
(function() {
  var bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; },
    extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty;

  window.App || (window.App = {});

  App.Shipments = (function(superClass) {
    extend(Shipments, superClass);

    function Shipments() {
      this.edit = bind(this.edit, this);
      this.beforeAction = bind(this.beforeAction, this);
      return Shipments.__super__.constructor.apply(this, arguments);
    }

    Shipments.prototype.beforeAction = function(action) {
      return console.log("before " + action + " action");
    };

    Shipments.prototype.edit = function() {
      return console.log("In Shipments Edit page!");
    };

    return Shipments;

  })(App.Base);

}).call(this);
```

Which contains the `console.log` line in the `edit` function, but the console shows nothing 😞 . I've even tried a plain `alert("Hello")`, to no avail. If I place a `console.log` call in `global.js.coffee` that works (but then again that's just loaded by Rails like any other JS file). I've also tried adding alerts and console logs to constructor of `base.js.coffee` like (excerpt):

```javascript
class App.Base

  constructor: ->
    if (window.jQuery) then @setClearEventHandlers() # clearing application event handlers only possible with jQuery
    console.log('boo')
    return this
```

But that doesn't fire either. Hope I'm including enough info to help. Any ideas?

Thanks!

**Comment by kpheasey** [comment]
There was an update a few days ago to add support for Turbolinks 5 and it changed the base.js.

Can you just copy the complete contents of your `base.js` and also your `application.js` or whatever JS manifest file you are using?

**Comment by edelgado** [comment]
Sure thing. Just as a note, I didn't have to upgrade because I just began using the gem today and it's already version 1.0.0. Here are the contents of `base.js.coffee`:

````javascript
window.App ||= {}
window.Element ||= {}
window.Utility ||= {}

$(document).on "turbolinks:load.rails_script",  ->
  Utility.RailsVars = $('#rails-script').data('vars')
  window.$this = new (App["#{$('#rails-script').data('controller')}"] || App.Base)()

class App.Base

  constructor: ->
    if (window.jQuery) then @setClearEventHandlers() # clearing application event handlers only possible with jQuery
    console.log('boo')
    return this


  ###
  Run the new action for the create action.  Generally the create action will 'render :new' if there was a problem.
  This prevents doubling the code for each action.
  ###
  create: ->
    if typeof $this.new == 'function'
      return $this.new()


  ###
  Run the edit action for the update action.  Generally the update action will 'render :edit' if there was a problem.
  This prevents doubling the code for each action.
  ###
  update: ->
    if typeof $this.edit == 'function'
      return $this.edit()


  ###
  Clear event handlers with a blank namespace.  This will prevent window and document event handlers from stacking
  when each new page is fetched.  Adding a namespace to your events will prevent them from being removed between page
  loads, i.e. "$(window).on 'scroll.app', myHandler"
  ###
  setClearEventHandlers: ->
    jQuery(document).on 'page:before-change', ->
      for element in [window, document]
        for event, handlers of (jQuery._data(element, 'events') || {})
          for handler in handlers
            if handler? && handler.namespace == ''
              jQuery(element).off event, handler.handler
````

And this is my `application.js`:

````javascript
// This is a manifest file that'll be compiled into application.js, which will include all the files
// listed below.
//
// Any JavaScript/Coffee file within this directory, lib/assets/javascripts, vendor/assets/javascripts,
// or any plugin's vendor/assets/javascripts directory can be referenced here using a relative path.
//
// It's not advisable to add code directly here, but if you do, it'll appear at the bottom of the
// compiled file.
//
// Read Sprockets README (https://github.com/rails/sprockets#sprockets-directives) for details
// about supported directives.
//
//= require jquery
//= require jquery_ujs
//= require turbolinks
//= require bootstrap-sprockets
//= require nested_form_fields
//= require base
//= require_tree ./utilities
//= require_tree ./elements
//= require_tree .
````

I've tried it without `nested_form_fields` just in case it was some sort of incompatibility, but the issue remained, so it wasn't it.

Thanks for your help so far.

**Comment by kpheasey** [comment]
Thanks for the info.  I'm looking into the issue now.  I realized I released v1 missing a large chunk of JS.  I'm doing some reworking to make the setup painless.

**Comment by kpheasey** [comment]
I just made a major overhaul because of this!  I converted this to an engine so you don't need to manually load files and initializers....  Everything is hidden away nicely.

Please use version 2.0 and read the migration wiki; https://github.com/gemgento/rails_script/wiki/v2-Migration

```
gem 'rails_script', '~> 2.0'
```

I have a test app that i'll upload if you are still having issues.

**Comment by cjjuice** [comment]
Having a similar issue after upgrading to 2.0 and rails 5. Seems like App.Base is not being initialized.

Going to get some dinner I will dig deeper later.

**Comment by kpheasey** [comment]
Make sure to include rails_script in the Javascript manifest,
application.js. That's where the initializer is now.

**Comment by cjjuice** [comment]
Yeah it's in there. 

Could it be that "turbolinks:load.rails_script" event is not firing here -> https://github.com/gemgento/rails_script/blob/master/vendor/assets/javascripts/rails_script/init.coffee#L6

**Comment by kpheasey** [comment]
Are you using and including turbolinks 5?

I should make it a gem dependency.

**Comment by cjjuice** [comment]
bingo. I was using 2.x.x 

I added 'turbolinks', '~> 5.0.0.beta' to gemfile and bundle updated and presto 👍

**Comment by kpheasey** [comment]
I suppose I can make it backwards compatible by binding to both events,
plus a non turbolinks event so it's not even a requirement.

**Comment by kpheasey** [comment]
I have added support for all versions of Turbolinks and removed any dependency on Turbolinks, in case someone isn't using it.

https://rubygems.org/gems/rails_script/versions/2.0.1

**Comment by kpheasey** [comment]
https://github.com/gemgento/rails_script/commit/ccb0d8a68083350695da20be015bd196d5dbbd27
