### ISSUE TITLE
Controller actions firing more than once (2.0.1)

### ISSUE THREAD

**Issue by cjjuice** [gemgento/rails_script#16]
```coffeescript
class App.Messages extends App.Base

  constructor: ->

  show: ->
    chat = new Utility.Chat

    d = $('#messages-list')
    d.scrollTop(d.prop("scrollHeight"))

    $(document).on 'keypress', (event) ->
      if event.keyCode == 13 # return = send
        if !event.shiftKey
          chat.stream.speak event.target.value
          $("#message-loader").css({opacity: 1})
          event.target.value = ''
          event.preventDefault()
```
They keypress event is stacking because show is being called more than once. Could this be because main rails_script handler is firing for both turbolinks and regular page change?

**Comment by kpheasey** [comment]
If you define show to just print to the console, do you see the message twice?

```
class App.Messages extends App.Base
  
  show: ->
    console.log 'messages#show'
    return
```

**Comment by cjjuice** [comment]
yeah already did that. Definitely firing more than once. 

Do you think it could be because it is firing on both page:load and turbolinks:load in https://github.com/gemgento/rails_script/blob/master/vendor/assets/javascripts/rails_script/init.coffee#L7 ?

**Comment by kpheasey** [comment]
@cjjuice Did you fix the problem?  If so, please make a pull request.  Otherwise, I will be looking into this today.

**Comment by cjjuice** [comment]
@kpheasey not yet. I just rolled back to 2.0.0

**Comment by cjjuice** [comment]
What about if there is a check for turbolinks and sets the event based on that.

**Comment by kpheasey** [comment]
The intiialzier uses different events based on the existence of Turbolinks; https://github.com/gemgento/rails_script/commit/6e7ca19d010467f2acfaf97474d0a79787d06ca4

Version 2.0.2 has been pushed.
