### ISSUE TITLE
<%= include_rails_script %> returning div

### ISSUE THREAD

**Issue by Bran99** [gemgento/rails_script#20]
I've followed the instructions for installation to the T.  I'm using rails 5 with the latest version of rails_script.  The contents of my `application.js` are

```
//= require jquery
//= require jquery-ui
//= require jquery_ujs
//= require jquery-fileupload
//= require bootstrap/util
//= require bootstrap/alert
//= require bootstrap/button
//= require bootstrap/carousel
//= require bootstrap/collapse
//= require bootstrap/dropdown
//= require bootstrap/modal
//= require bootstrap/scrollspy
//= require bootstrap/tab
//= require turbolinks
//= require_tree .

//= require rails_script
```

and the contents of my `application.haml` are

```
!!!
%html
  %head
    %title My Project
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': true
    = javascript_include_tag 'application', 'data-turbolinks-track': true
  %body
    ...
    = include_rails_script
```

Still I'm getting a returned `div` as opposed to the `<script>` tag I'm expecting.  Any ideas why this is happening?

I also assume that this is the cause of my js error in the console which appears once per rails_script file:
`Uncaught TypeError: Cannot read property 'prototype' of undefined`

**Comment by Bran99** [comment]
I've searched around and I see this isn't a bug, but rather a feature.  Still I'm having the issue of the javascript not firing.

**Comment by Bran99** [comment]
The javascript tag generated by my manifest is
```
<script src="/assets/rails_script.self-877aef30ae1b040ab8a3aba4e3e309a11d7f2612f44dde450b5c157aa5f95c05.js?body=1" data-turbolinks-track="true"></script>
```
of which the contents are
```
(function() {


}).call(this);
```

**Comment by kpheasey** [comment]
@Bran99 You should be requiring rails_script before you require the tree.

```js
//= require jquery
//= require jquery-ui
//= require jquery_ujs
//= require jquery-fileupload
//= require bootstrap/util
//= require bootstrap/alert
//= require bootstrap/button
//= require bootstrap/carousel
//= require bootstrap/collapse
//= require bootstrap/dropdown
//= require bootstrap/modal
//= require bootstrap/scrollspy
//= require bootstrap/tab
//= require turbolinks
//= require rails_script
//= require_tree .
```

The `include_rails_script` helper prints out HTML not JS.  The div it creates has data attributes that the rails script initializer uses to call the correct JS.

**Comment by Bran99** [comment]
Awesome!  Thanks @kpheasey that fixed it.
