### ISSUE TITLE
No rails 5 support?

### ISSUE THREAD

**Issue by ammarshah** [gemgento/rails_script#21]
![screenshot from 2017-05-10 01 04 52](https://cloud.githubusercontent.com/assets/8036051/25870243/d8e7eac4-351c-11e7-90e2-fd23d84a12bf.png)

**Comment by kpheasey** [comment]
Can you copy your `application.js`?

**Comment by ammarshah** [comment]
Here you go @kpheasey 

```
// app/assets/javascripts/application.js

//= require jquery
//= require jquery_ujs
//= require tether
//= require bootstrap-sprockets
//= require_tree .

//= require rails_script
```

**Comment by ammarshah** [comment]
Oops! Sorry, my bad. I didn't notice that `//= require rails_script` should be before `//= require_tree .`.
But I think rather than adding this line through the generator, it'd be better if it's prompted after running a generator like the one with `<%= include_rails_script %>` this to be added in application layout, just a suggestion though. :)

**Comment by kpheasey** [comment]
The generator does seem to be problematic.... It might be better to remove it from the generator and just add it to the setup section of the readme.

I'm happy to accept a PR for it too!  Otherwise, I will get to it at some point in time.
