### ISSUE TITLE
How to set controller specific variables available to all functions?

### ISSUE THREAD

**Issue by runar** [gemgento/rails_script#4]
So, I need to store the values of some page elements as variables available to all controller actions and functions.

I have tried the following and several variants without any success:

```coffeescript
window.App ||= {}
class App.Users extends App.Base

  someVar: $('.element').val()

  show: =>
    console.log @someVar
```

I found one way that does work, but it feels … wrong:

```coffeescript
  show: =>
    console.log @values().someVar

  values: =>
    {  someVar: $('.element').val() }
```

Maybe I am missing something here, but how can I do this with RailsScript?

**Comment by cjjuice** [comment]
how is this?

```coffeescript
window.App ||= {}
class App.Users extends App.Base

  beforeAction: => 
    @someVar = $('.element').val()

  show: =>
  console.log @someVar  

  edit: =>
    console.log @someVar

**Comment by runar** [comment]
@cjjuice that seems to do the trick, thank you! :smile:
