### ISSUE TITLE
Is 'include_rails_script.js.coffee' file still useful?

### ISSUE THREAD

**Issue by tortuetorche** [gemgento/rails_script#6]
See: https://github.com/gemgento/rails_script/blob/v0.6.1/include_rails_script.js.coffee

Because its code looks duplicated in this file:  https://github.com/gemgento/rails_script/blob/v0.6.1/lib/rails_script/loader_helper.rb#L6

**Comment by kpheasey** [comment]
That was being left in there as a reference file if you didn't want to use the helper.  I'll remove it in a future release as it has been added to the wiki.

**Comment by tortuetorche** [comment]
OK, thank you for your answer.
