### ISSUE TITLE
Uncaught TypeError: (App.Home || App.Base) is not a function

### ISSUE THREAD

**Issue by vanboom** [gemgento/rails_script#7]
I installed and set up per the README, and am getting this javascript error when my page loads... my root controller is HomeController

It appears to be coming from the code injected by the include_rails_script addition to the application layout.   Maybe there is a dependency order that is out of line? 

```javascript
(function() {
  window.$this = new (App.Home || App.Base)();
  if (typeof $this.beforeAction === 'function') {
    $this.beforeAction("index");
  }
  if (typeof $this.index === 'function') {
    $this.index();
  }
  if (typeof $this.afterAction === 'function') {
    $this.afterAction("index");
  }
})();
```

Thanks!  This gem seems like a super cool way to integrate JS into Rails if I can get it working.

**Comment by kpheasey** [comment]
What does your application.js manifest look like?  Where on the page are
you including the application.js?

On Tue, Sep 15, 2015 at 11:16 AM, Don <notifications@github.com> wrote:

> I installed and set up per the README, and am getting this javascript
> error when my page loads... my root controller is HomeController
>
> It appears to be coming from the code injected by the include_rails_script
> addition to the application layout. Maybe there is a dependency order that
> is out of line?
>
> (function() {
>   window.$this = new (App.Home || App.Base)();
>   if (typeof $this.beforeAction === 'function') {
>     $this.beforeAction("index");
>   }
>   if (typeof $this.index === 'function') {
>     $this.index();
>   }
>   if (typeof $this.afterAction === 'function') {
>     $this.afterAction("index");
>   }
> })();
>
> Thanks! This gem seems like a super cool way to integrate JS into Rails if
> I can get it working.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/gemgento/rails_script/issues/7>.
>



-- 
Regards,
Kevin Pheasey
(203) 247-1881

**Comment by vanboom** [comment]
With apologies... I had to move quickly and decided to use the Gon gem.  I will revisit this as soon as my time permits.

**Comment by GeoffreyBooth** [comment]
I had the same issue. I foolishly thought I was supposed to remove `<%= javascript_include_tag "application" %>` and delete `app/assets/javascripts/application.js`. Lesson learned.

**Comment by kpheasey** [comment]
@GeoffreyBooth I have updated the readme with a note about this in the installation section.

https://github.com/gemgento/rails_script/commit/39af3340b6ed961b203100e38effbf656a88ae53
